//! Seed data: compliance, specialized, design, release, research (22 agents).

use crate::types::{AgentCategory, AgentInput};

fn ag(
    name: &str,
    role: &str,
    cat: AgentCategory,
    tier: &str,
    esc: Option<&str>,
    caps: &[&str],
) -> AgentInput {
    AgentInput {
        name: name.into(),
        role: role.into(),
        org: "convergio".into(),
        category: cat,
        model_tier: tier.into(),
        max_tokens: 200_000,
        hourly_budget: 0.0,
        capabilities: caps.iter().map(|s| s.to_string()).collect(),
        prompt_ref: None,
        escalation_target: esc.map(Into::into),
    }
}

pub fn agents() -> Vec<AgentInput> {
    use AgentCategory::*;
    vec![
        ag(
            "elena",
            "Compliance officer — GDPR, legal review",
            ComplianceLegal,
            "t3",
            Some("ali-orchestrator"),
            &["compliance", "gdpr", "legal-review", "privacy"],
        ),
        ag(
            "luca",
            "Legal counsel — contracts and IP",
            ComplianceLegal,
            "t3",
            Some("elena"),
            &["legal", "contracts", "intellectual-property", "licensing"],
        ),
        ag(
            "guardian",
            "Security guardian — access and secrets",
            ComplianceLegal,
            "t3",
            Some("sentinel"),
            &[
                "security",
                "secrets-management",
                "access-control",
                "vulnerability-scanning",
            ],
        ),
        ag(
            "dr-enzo",
            "Ethics advisor — AI alignment",
            ComplianceLegal,
            "t3",
            Some("ali-orchestrator"),
            &["ai-ethics", "alignment", "bias-detection", "responsible-ai"],
        ),
        ag(
            "sophia",
            "Privacy engineer — data minimization",
            ComplianceLegal,
            "t2",
            Some("elena"),
            &["privacy", "data-minimization", "pii-detection", "consent"],
        ),
        ag(
            "fiona",
            "Database expert — schema and query optimization",
            SpecializedExperts,
            "t3",
            Some("baccio"),
            &[
                "database",
                "sql",
                "sqlite",
                "schema-design",
                "query-optimization",
            ],
        ),
        ag(
            "sam",
            "Infra specialist — networking and deployment",
            SpecializedExperts,
            "t3",
            Some("marco-devops"),
            &["infrastructure", "networking", "deployment", "cloud", "ssh"],
        ),
        ag(
            "wiz",
            "API wizard — design and integration expert",
            SpecializedExperts,
            "t3",
            Some("baccio"),
            &["api-design", "rest", "integration", "openapi", "rust"],
        ),
        ag(
            "behice",
            "Testing expert — strategy and automation",
            SpecializedExperts,
            "t3",
            Some("thor"),
            &["testing", "test-strategy", "automation", "e2e", "rust"],
        ),
        ag(
            "coach",
            "Developer coach — mentoring and onboarding",
            SpecializedExperts,
            "t2",
            Some("ali-orchestrator"),
            &["mentoring", "onboarding", "developer-experience"],
        ),
        ag(
            "giulia",
            "Localization expert — i18n and l10n",
            SpecializedExperts,
            "t2",
            Some("ali-orchestrator"),
            &["localization", "i18n", "translation", "multilingual"],
        ),
        ag(
            "jenny",
            "AI prompt engineer — prompt crafting",
            SpecializedExperts,
            "t3",
            Some("ali-orchestrator"),
            &[
                "prompt-engineering",
                "llm",
                "context-design",
                "system-prompts",
            ],
        ),
        ag(
            "jony",
            "Chief designer — UI/UX vision",
            DesignUx,
            "t3",
            Some("matteo"),
            &["ui-design", "ux", "design-system", "visual-design"],
        ),
        ag(
            "sara",
            "UX researcher — user testing and flows",
            DesignUx,
            "t2",
            Some("jony"),
            &[
                "ux-research",
                "usability-testing",
                "user-flows",
                "accessibility",
            ],
        ),
        ag(
            "nasra",
            "Visual designer — brand and components",
            DesignUx,
            "t2",
            Some("jony"),
            &["visual-design", "brand", "components", "figma"],
        ),
        ag(
            "stefano",
            "Frontend architect — design system impl",
            DesignUx,
            "t3",
            Some("jony"),
            &["frontend", "react", "typescript", "design-system", "css"],
        ),
        ag(
            "app-release-manager-ios",
            "iOS app release manager",
            ReleaseManagement,
            "t2",
            Some("marco-devops"),
            &["ios", "release-management", "app-store", "xcode"],
        ),
        ag(
            "app-release-manager-android",
            "Android app release manager",
            ReleaseManagement,
            "t2",
            Some("marco-devops"),
            &["android", "release-management", "play-store", "gradle"],
        ),
        ag(
            "ecosystem-sync",
            "Ecosystem sync — cross-repo coordination",
            ReleaseManagement,
            "t2",
            Some("ali-orchestrator"),
            &["cross-repo", "coordination", "sync", "multi-project"],
        ),
        ag(
            "feature-release-manager",
            "Feature flag and rollout manager",
            ReleaseManagement,
            "t2",
            Some("marco-devops"),
            &["feature-flags", "rollout", "a-b-testing", "gradual-release"],
        ),
        ag(
            "mirrorbuddy",
            "Mirror buddy — fork and sync management",
            ReleaseManagement,
            "t1",
            Some("marco-devops"),
            &["git", "fork-management", "sync", "mirroring"],
        ),
        ag(
            "research-report-generator",
            "CTT research report generator — API-driven via /api/reports",
            ResearchReport,
            "t1",
            Some("ali-orchestrator"),
            &[
                "research",
                "report-generation",
                "analysis",
                "structured-output",
            ],
        ),
    ]
}
